services:
  autoplayer:
    build: .
    container_name: conquertactoe_autoplayer
    ports:
      - "8000:8000"
    environment:
      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST:-clickhouse}
      - CLICKHOUSE_PORT=${CLICKHOUSE_PORT:-9000}
      - CLICKHOUSE_DB=${CLICKHOUSE_DB:-default}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER:-default}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD:-}
    networks:
      - conquer-network
    depends_on:
      - clickhouse

  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: conquertactoe_clickhouse
    environment:
      - CLICKHOUSE_DB=${CLICKHOUSE_DB:-default}
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD:-}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER:-default}
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse-config/users.xml:/etc/clickhouse-server/users.d/users.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - conquer-network

networks:
  conquer-network:
    external: true

volumes:
  clickhouse_data:
