services:
  frontend:
    build:
      context: .
    container_name: conquertactoe_frontend
    ports:
      - "${FRONTEND_HOST_PORT}:${FRONTEND_CONTAINER_PORT}"
    networks:
      - conquer-network

networks:
  conquer-network:
    external: true
