services:
  frontend:
    build:
      context: .
    container_name: conquertactoe_frontend
    ports:
      - "${FRONTEND_HOST_PORT}:${FRONTEND_CONTAINER_PORT}"
    networks:
      - conquer-network
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"

networks:
  conquer-network:
    external: true
